/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new school/tenant */
        post: operations["AuthController_registerTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login to a tenant account */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all branches/groups for this org */
        get: operations["BranchesController_findAll"];
        put?: never;
        /** Create a new branch/group */
        post: operations["BranchesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch by ID */
        get: operations["BranchesController_findOne"];
        put?: never;
        post?: never;
        /** Deactivate a branch (only if no active students) */
        delete: operations["BranchesController_deactivate"];
        options?: never;
        head?: never;
        /** Update branch */
        patch: operations["BranchesController_update"];
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List students — filter by branchId, search, status */
        get: operations["StudentsController_findAll"];
        put?: never;
        /** Create a new student */
        post: operations["StudentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get student by ID */
        get: operations["StudentsController_findOne"];
        put?: never;
        post?: never;
        /** Archive student (soft delete) */
        delete: operations["StudentsController_remove"];
        options?: never;
        head?: never;
        /** Update student */
        patch: operations["StudentsController_update"];
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics — optionally filtered by branchId */
        get: operations["DashboardController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attendance for a specific date */
        get: operations["AttendanceController_getAttendance"];
        put?: never;
        /** Record attendance for students */
        post: operations["AttendanceController_recordAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform user login (OWNER or SALES) */
        post: operations["PlatformController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tenants — OWNER + SALES */
        get: operations["PlatformController_listTenants"];
        put?: never;
        /** Create a new tenant for a client — OWNER + SALES */
        post: operations["PlatformController_createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/tenants/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate / deactivate a tenant — OWNER only */
        patch: operations["PlatformController_toggleTenant"];
        trace?: never;
    };
    "/api/platform/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform-wide stats — OWNER only */
        get: operations["PlatformController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List platform users (OWNER + SALES accounts) — OWNER only */
        get: operations["PlatformController_listUsers"];
        put?: never;
        /** Create a SALES platform user — OWNER only */
        post: operations["PlatformController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InitialBranchDto: {
            /** @example الفرع الرئيسي */
            name: string;
            /** @example المعادي */
            area?: string;
            /**
             * @description للمدارس فقط: أنواع المناهج
             * @example [
             *       "LANGUAGES"
             *     ]
             */
            curriculums?: ("ARABIC" | "LANGUAGES" | "IG")[];
            /**
             * @description للمدارس فقط: PRIVATE | GOVERNMENT
             * @example PRIVATE
             */
            ownership?: string;
        };
        RegisterTenantDto: {
            /** @example مدرسة النور */
            tenantName: string;
            /**
             * @description Subdomain (lowercase, no spaces)
             * @example alnoor
             */
            subdomain: string;
            /**
             * @example SCHOOL
             * @enum {string}
             */
            orgType: "SCHOOL" | "CENTER" | "PRIVATE_TUTOR";
            initialBranch: components["schemas"]["InitialBranchDto"];
            /** @example admin@alnoor.com */
            adminEmail: string;
            /** @example StrongPassword123! */
            adminPassword: string;
            /** @example أحمد محمد */
            adminName: string;
        };
        LoginDto: {
            /** @example admin@school.com */
            email: string;
            /** @example password123 */
            password: string;
            /**
             * @description School subdomain
             * @example alnoor
             */
            subdomain: string;
        };
        CreateBranchDto: {
            /** @example فرع المعادي */
            name: string;
            /** @example المعادي */
            area?: string;
            /**
             * @description أنواع المناهج — للمدارس فقط
             * @example [
             *       "LANGUAGES"
             *     ]
             */
            curriculums?: ("ARABIC" | "LANGUAGES" | "IG")[];
            /**
             * @description نوع الملكية — للمدارس فقط: PRIVATE | GOVERNMENT
             * @example PRIVATE
             */
            ownership?: string;
            /** @example false */
            isMain?: boolean;
        };
        UpdateBranchDto: {
            /** @example فرع المعادي */
            name?: string;
            /** @example المعادي */
            area?: string;
            /**
             * @description أنواع المناهج — للمدارس فقط
             * @example [
             *       "LANGUAGES"
             *     ]
             */
            curriculums?: ("ARABIC" | "LANGUAGES" | "IG")[];
            /**
             * @description نوع الملكية — للمدارس فقط: PRIVATE | GOVERNMENT
             * @example PRIVATE
             */
            ownership?: string;
            /** @example false */
            isMain?: boolean;
        };
        CreateStudentDto: {
            /**
             * @description ID الفرع
             * @example branch_id_here
             */
            branchId: string;
            /** @example محمد أحمد */
            name: string;
            /** @example student@example.com */
            email?: string;
            /** @example 01012345678 */
            phone?: string;
            /** @example أحمد محمد */
            parentName?: string;
            /** @example 01098765432 */
            parentPhone?: string;
            /** @example الصف الثالث الإعدادي */
            grade?: string;
            /** @example مجموعة أ */
            className?: string;
            notes?: string;
        };
        UpdateStudentDto: {
            /**
             * @description ID الفرع
             * @example branch_id_here
             */
            branchId?: string;
            /** @example محمد أحمد */
            name?: string;
            /** @example student@example.com */
            email?: string;
            /** @example 01012345678 */
            phone?: string;
            /** @example أحمد محمد */
            parentName?: string;
            /** @example 01098765432 */
            parentPhone?: string;
            /** @example الصف الثالث الإعدادي */
            grade?: string;
            /** @example مجموعة أ */
            className?: string;
            notes?: string;
        };
        AttendanceEntryDto: Record<string, never>;
        RecordAttendanceDto: {
            /** @example 2024-01-15 */
            date: string;
            records: components["schemas"]["AttendanceEntryDto"][];
        };
        PlatformLoginDto: {
            /** @example mohammedosama@gmail.com */
            email: string;
            /** @example Lumi@Owner2025! */
            password: string;
        };
        PlatformInitialBranchDto: {
            /** @example الفرع الرئيسي */
            name: string;
            /** @example المعادي */
            area?: string;
            /**
             * @description للمدارس فقط: أنواع المناهج
             * @example [
             *       "LANGUAGES"
             *     ]
             */
            curriculums?: ("ARABIC" | "LANGUAGES" | "IG")[];
            /**
             * @description للمدارس فقط: PRIVATE | GOVERNMENT
             * @example PRIVATE
             */
            ownership?: string;
        };
        CreateTenantPlatformDto: {
            /** @example مدرسة النور */
            tenantName: string;
            /**
             * @description Subdomain (lowercase, no spaces)
             * @example alnoor
             */
            subdomain: string;
            /**
             * @example SCHOOL
             * @enum {string}
             */
            orgType: "SCHOOL" | "CENTER" | "PRIVATE_TUTOR";
            initialBranch: components["schemas"]["PlatformInitialBranchDto"];
            /** @example admin@alnoor.com */
            adminEmail: string;
            /** @example StrongPassword123! */
            adminPassword: string;
            /** @example أحمد محمد */
            adminName: string;
        };
        CreatePlatformUserDto: {
            /** @example sales2@lumi.app */
            email: string;
            /** @example موظف مبيعات */
            name: string;
            /** @example Sales@Lumi123! */
            password: string;
            /**
             * @default SALES
             * @enum {string}
             */
            role: "OWNER" | "SALES";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_registerTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBranchDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_findAll: {
        parameters: {
            query: {
                branchId: string;
                search: string;
                status: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getStats: {
        parameters: {
            query: {
                branchId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttendanceController_getAttendance: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttendanceController_recordAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordAttendanceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformLoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantPlatformDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_toggleTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlatformUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
